cd ./source\repos\Studium\04_BigDataCloudNoSQL\BCN-2026SSTeamMagenta-Sensiq\sys-doc\concept_paper\src\
@REM Delete auxiliary files generated by LaTeX compilation
del *.aux
del *.bbl
del *.bcf
del *.blg
del *.log
del *.out
del *.run.xml
del *.tex.bbl
del *.tex.blg
del *.upa
del *.upb


pdflatex main
pdflatex main
biber main
pdflatex main
pdflatex main